### ISSUE TITLE
Dynamic Sizing of Cell height with Image dimensions

### ISSUE THREAD

**Issue by Neeraj3pathi** [Neeraj3pathi/SimpleDrawing#2]
[DynamicCell.zip](https://github.com/Neeraj3pathi/SimpleDrawing/files/368624/DynamicCell.zip)

**Comment by Aravind6** [comment]
[DynamicCell.zip](https://github.com/Neeraj3pathi/SimpleDrawing/files/369285/DynamicCell.zip)

**Comment by supermnemonic** [comment]
hey. i have same problem . did you solved it ?
